baseURL = 'https://rivit.dev/'
# [en, zh-cn, fr, pl, ...] determines default content language
defaultContentLanguage = "en"
# theme
theme = "DoIt"

# website title
title = "Rivit's blog"

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
enableGitInfo = false
# whether to use emoji code
enableEmoji = false

# ignore some build errors
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

languageCode = "en"
# language name
languageName = "English"
# whether to include Chinese/Japanese/Korean
hasCJKLanguage = false
# [UA-XXXXXXXX-X] google analytics code (replaced by params.analytics.google)
googleAnalytics = "G-P8PM36X0J7"

[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "Tags"
    url = "/categories/"
    weight = 3
