# baseURL = 'https://rivit.dev/'
# baseURL = 'http://192.168.56.3:1313/'
baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = "Rivit's blog"
paginate = 10
theme = 'hugo-theme-stack'

DefaultContentLanguage = "en"
hasCJKLanguage = false


