baseURL = 'https://rivit.dev/'

languageCode = 'en-us'
title = "Rivit's blog"
paginate = 10
theme = 'hugo-theme-stack'

DefaultContentLanguage = "en"
hasCJKLanguage = false

[imaging]
  resampleFilter = "lanczos"
  quality = 100
  anchor = "smart"
  hint = "text"
