# Markdown renderer configuration
[goldmark]
  [goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [goldmark.renderer]
    # whether to use HTML tags directly in the document
    unsafe = true

[tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

[highlight]
# noClasses = false
codeFences = true
guessSyntax = false

# https://github.com/alecthomas/chroma/tree/master/styles
# style="catppuccin-frappe"
style="monokai"
