# site description
description = "Rivit's blog"

[author]
  name = "Rivit"

# site default theme ("light", "dark", "black", "auto")
defaultTheme = "dark"
# date format
dateFormat = "2006-01-02"
# Header config
[header]
  # desktop header mode ("fixed", "normal", "auto")
  desktopMode = "fixed"
  # mobile header mode ("fixed", "normal", "auto")
  mobileMode = "fixed"
  # theme change mode ("switch", "select")
  themeChangeMode = "switch"
  # Header title config
  [header.title]
    # title name
    name = "Rivit's blog"
    # whether to use typeit animation for title name
    typeit = false
    post = ""

# Footer config
[footer]
  enable = true
  # whether to show Hugo and theme info
  hugo = false
  # whether to show copyright info
  copyright = true
  # whether to show the author
  author = false
  # site creation time
  since = 2021
  # license info (HTML format is supported)
  license= ''

# Section (all posts) page config
[section]
  # special amount of posts in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "2006-01-02"
  # amount of RSS pages
  rss = 10
  # recently updated posts settings
  [section.recentlyUpdated]
    enable = false
    rss = true
    days = 30
    maxCount = 10

# List (category or tag) page config
[list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "2006-01-02"
  # amount of RSS pages
  rss = 10

# Page config
[page]
  # whether to hide a page from home page
  hiddenFromHomePage = false
  # whether to hide a page from search results
  hiddenFromSearch = false
  # whether to enable twemoji
  twemoji = false
  # whether to enable lightgallery
  lightgallery = true
  # whether to enable the ruby extended syntax
  ruby = false
  # whether to enable the fraction extended syntax
  fraction = false
  # whether to show link to Raw Markdown content of the content
  linkToMarkdown = false
  # whether to show the full text content in RSS
  rssFullText = false
  # whether to enable last modified time
  enableLastMod = false
  # whether to enable word count
  enableWordCount = false
  # whether to enable reading time estimation
  enableReadingTime = false

  # Display a message at the beginning of an article to warn the reader that its content might be outdated.
  [page.toc]
    # whether to enable the table of the contents
    enable = true
    # whether to keep the static table of the contents in front of the post
    keepStatic = false
    # whether to make the table of the contents in the sidebar automatically collapsed
    auto = true
  # Code config
  [page.code]
    # whether to show the copy button of the code block
    copy = true
    # the maximum number of lines of displayed code by default
    maxShownLines = 10000
  # Table config
  [page.table]
    # whether to enable sorting in the tables
    sort = true
  [page.header]
    # whether to enable auto header numbering
    [page.header.number]
      enable = false
      [page.header.number.format]
        h2 = "{h2} {title}"
        h3 = "{h2}.{h3} {title}"
        h4 = "{h2}.{h3}.{h4} {title}"
        h5 = "{h2}.{h3}.{h4}.{h5} {title}"
        h6 = "{h2}.{h3}.{h4}.{h5}.{h6} {title}"
  # KaTeX mathematical formulas config (KaTeX https://katex.org/)
  [page.math]
    enable = false

  # Social share links in post page
  [page.share]
    enable = true
    HackerNews = true
    Reddit = true
    Twitter = true
    # X = true # TODO: make a PR
    Mastodon = true

  # Page SEO config
  [page.seo]
    # image URL
    images = []
    # Publisher info
    [page.seo.publisher]
      name = "Rivit"
      logoUrl = "/img/avatar.webp"
  # Related content config
  [page.related]
    enable = false
    count = 5

# Site verification code for Google/Bing/Yandex/Pinterest/Baidu
[verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""
  so = ""
  sogou = ""

# Analytics config
[analytics]
  enable = true
  # Google Analytics
  [analytics.google]
    id = "G-P8PM36X0J7"
    # whether to anonymize IP
    anonymizeIP = true

# Cookie consent config
[cookieconsent]
  enable = false
  # text strings used for Cookie consent banner
  [cookieconsent.content]
    message = ""
    dismiss = ""
    link = ""

# CDN config for third-party library files
[cdn]
  # CDN data file name, disabled by default
  # ("jsdelivr.yml")
  # located in "themes/DoIt/assets/data/cdn/" directory
  # you can store your own data files in the same path under your project:
  # "assets/data/cdn/"
  data = ""

# Compatibility config
[compatibility]
  # whether to use Polyfill.io to be compatible with older browsers
  polyfill = false
  # whether to use object-fit-images to be compatible with older browsers
  objectFit = false


# Search config
[search]
  enable = true
  # type of search engine ("algolia", "fuse")
  type = "pagefind"
  # max index length of the chunked content
  contentLength = 4000
  # placeholder of the search bar
  placeholder = ""
  # max number of results length
  maxResultLength = 10
  # snippet length of the result
  snippetLength = 40
  # HTML tag name of the highlight part in results
  highlightTag = "em"
  # whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false

  [search.pagefind]
    # https://pagefind.app/docs/search-config/#available-options
    # run `npx pagefind --site $YOUR_PUBLIC_DIR` after site build to create pagefind index
    termFrequency = 1.0
    pageLength = 0.75
    termSimilarity = 1.0
    termSaturation = 1.4

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Home page config
[home]
  # amount of RSS pages
  rss = 10
  # Home page profile
  [home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/img/avatar.webp"
    # URL the avatar links to
    avatarLinkURL = ""
    # title shown in home page (HTML format is supported)
    title = "Rivit"
    # subtitle shown in home page
    subtitle = "ctf writeups, security research and findings"
    # whether to use typeit animation for subtitle
    typeit = false
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
  # Home page posts
  [home.posts]
    enable = true
    # special amount of posts in each home posts page
    paginate = 10


[social]
  Email = "albert98g@gmail.com"
  GitHub = "rivit98"
  RSS = true
  X = "rivit98"
  Discord = "513014269932077067"


[image]
  # image lazy loading
  false = true
  # image gallery support
  gallery = false