# Privacy config (https://gohugo.io/about/hugo-and-gdpr/)

# privacy of the Google Analytics (replaced by params.analytics.google)
[googleAnalytics]
  # ...
[x]
  enableDNT = true
[youtube]
  privacyEnhanced = true
