FROM golang:latest as builder

ENV GOCACHE=/root/.cache/go-build
RUN --mount=type=cache,target="/root/.cache/go-build" CGO_ENABLED=1 go install -tags extended github.com/gohugoio/hugo@v0.123.0


WORKDIR /app
COPY . .
